management_enrollment:
    resource: "@ManagementEnrollmentBundle/Controller/"
    type:     annotation
    prefix:   /enrollment

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
    prefix:   /
