management_meeting:
    resource: "@ManagementMeetingBundle/Controller/"
    type:     annotation
    prefix:   /meeting

management_user:
    resource: "@ManagementUserBundle/Controller/"
    type:     annotation
    prefix:   /account

management_enrollment:
    resource: "@ManagementEnrollmentBundle/Controller/"
    type:     annotation
    prefix:   /enrollment

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
    prefix:   /

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
