organization_log:
    resource: "@OrganizationLogBundle/Controller/"
    type:     annotation
    prefix:   /

organization_management:
    resource: "@OrganizationManagementBundle/Controller/"
    type:     annotation
    prefix:   /management

organization_user:
    resource: "@OrganizationUserBundle/Controller/"
    type:     annotation
    prefix:   /account

organization_enrollment:
    resource: "@OrganizationEnrollmentBundle/Controller/"
    type:     annotation
    prefix:   /enrollment

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
    prefix:   /

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
