# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    # do not use locale listener, bur force from configuration
    # managementapp.listener.request:
    #     class: AppBundle\Services\LocaleListener
    #     arguments: ["%kernel.default_locale%"]
    #     tags:
    #         - { name: kernel.event_subscriber }

    twig.extension.text:
         class: Twig_Extensions_Extension_Text
         tags:
             - { name: twig.extension }

    twig.extension.debug:
        class: Twig_Extension_Debug
        tags:
            - { name: twig.extension }
        # {% debug variabletodump %}
