stof_doctrine_extensions:
    orm:
        default:
            timestampable:  true
            blameable:      true
            loggable:       true
            softdeleteable: true
            # uploadable:   true
