stof_doctrine_extensions:
    default_locale: %locale%
    orm:
        default:
            timestampable:  true
            blameable:      true
            loggable:       true
            softdeleteable: true
            # uploadable:   true
