services:
    management.menu.twig.extension:
        class: Organization\ManagementBundle\Twig\MenuExtension
        arguments: [@doctrine.orm.default_entity_manager]
        tags:
          - { name: twig.extension }

